# Workflow for deploying static content to GitHub Pages and building Node.js app
name: Build and Deploy Static Content

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version to use

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build  # Replace with your build script if applicable

      - name: Run server
        run: |
          npm start &  # Start the server in the background
          sleep 10     # Wait for the server to start

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Adjust path if necessary

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    # Optionally, you might want to add a step to stop the server after deployment
    # - name: Stop server
    #   run: pkill -f 'node server.js'
